### ISSUE TITLE
patchv380.exe

### ISSUE THREAD

**Issue by goodboyit** [bcaller/v380-ipcam-firmware-patch#1]
Hi Dear
I got below error when i compile your software. What is this error?
error: 'patchv380.exe' requires a subcommand, but one was not provided

**Comment by bcaller** [comment]
If you run `./patchv380 --help` it will show the subcommands are `read` or `write`.

For more information about the subcommand use `./patchv380 read --help`.

E.g. to list files in a patch file called `my.patch`, run `./patchv380 read my.patch`.

Hope that helps you.
